#!/usr/bin/env python

import sys

import autopy

from screen import get_current_grid
import board


if __name__ == '__main__':
   if len(sys.argv) < 2:
      print "Usage: src/show_jewel_on_board <path to image>"
      sys.exit(1)
      
   path = sys.argv[1]
   bitmap = autopy.bitmap.Bitmap.open(path)

   try:
      for row in get_current_grid(bitmap):
         print "\t".join(row)
      
   except board.NotVisible:
      print "No board visible on that image."
      sys.exit(2)
